from scrapers.common.country_config import CountryConfig

# ---------------------------------------------------------------------------
# Afrique francophone — même plateforme, paths /recruteur/ et /recruteurs
# ---------------------------------------------------------------------------
COUNTRIES: dict[str, CountryConfig] = {
    "maroc": CountryConfig(
        code="maroc",
        base_url="https://www.emploi.ma",
        jobs_search_path="/recherche-jobs-maroc",
    ),
    "cote_ivoire": CountryConfig(
        code="cote_ivoire",
        base_url="https://www.emploi.ci",
        jobs_search_path="/recherche-jobs-cote-ivoire",
        cv_storage_path="/sites/emploi.ci/files/private/cv/",
    ),
    "congo": CountryConfig(
        code="congo",
        base_url="https://www.emploi.cg",
        jobs_search_path="/recherche-jobs-congo-brazzaville",
        cv_storage_path="/sites/emploi.cg/files/private/cv/",
    ),
    "cameroun": CountryConfig(
        code="cameroun",
        base_url="https://www.emploi.cm",
        jobs_search_path="/recherche-jobs-cameroun",
        cv_storage_path="/sites/emploi.cm/files/private/cv/",
    ),
    "senegal": CountryConfig(
        code="senegal",
        base_url="https://www.emploisenegal.com",
        jobs_search_path="/recherche-jobs-senegal",
        cv_storage_path="/sites/emploisenegal.com/files/private/cv/",
    ),
    "burkina": CountryConfig(
        code="burkina",
        base_url="https://www.emploiburkina.com",
        jobs_search_path="/recherche-jobs-burkina-faso",
        cv_storage_path="/sites/emploiburkina.com/files/private/cv/",
    ),
    "guinee": CountryConfig(
        code="guinee",
        base_url="https://www.emploiguinee.com",
        jobs_search_path="/recherche-jobs-guinee",
        cv_storage_path="/sites/emploiguinee.com/files/private/cv/",
    ),
    "togo": CountryConfig(
        code="togo",
        base_url="https://www.emploi.tg",
        jobs_search_path="/recherche-jobs-togo",
        cv_storage_path="/sites/emploi.tg/files/private/cv/",
    ),
    "gabon": CountryConfig(
        code="gabon",
        base_url="https://www.emploi.ga",
        jobs_search_path="/recherche-jobs-gabon",
        cv_storage_path="/sites/emploi.ga/files/private/cv/",
    ),
    "mauritanie": CountryConfig(
        code="mauritanie",
        base_url="https://www.emploimauritanie.com",
        jobs_search_path="/recherche-jobs-mauritanie",
        cv_storage_path="/sites/emploimauritanie.com/files/private/cv/",
    ),
    "benin": CountryConfig(
        code="benin",
        base_url="https://www.emploibenin.com",
        jobs_search_path="/recherche-jobs-benin",
        cv_storage_path="/sites/emploibenin.com/files/private/cv/",
    ),
    "mali": CountryConfig(
        code="mali",
        base_url="https://www.emploimali.com",
        jobs_search_path="/recherche-jobs-mali",
        cv_storage_path="/sites/emploimali.com/files/private/cv/",
    ),
    "congo_rdc": CountryConfig(
        code="congo_rdc",
        base_url="https://www.emploi.cd",
        jobs_search_path="/recherche-jobs-congo-rdc",
        cv_storage_path="/sites/emploi.cd/files/private/cv/",
    ),
    "algerie": CountryConfig(
        code="algerie",
        base_url="https://www.algeriejob.com",
        jobs_search_path="/recherche-jobs-algerie",
        cv_storage_path="/sites/algeriejob.com/files/private/cv/",
    ),
    "tunisie": CountryConfig(
        code="tunisie",
        base_url="https://www.emploitunisie.com",
        jobs_search_path="/recherche-jobs-tunisie",
        cv_storage_path="/sites/emploitunisie.com/files/private/cv/",
    ),
    "niger": CountryConfig(
        code="niger",
        base_url="https://www.nigerjob.net",
        jobs_search_path="/recherche-jobs-niger",
        cv_storage_path="/sites/nigerjob.net/files/private/cv/",
    ),
    "tchad": CountryConfig(
        code="tchad",
        base_url="https://www.emploi.td",
        jobs_search_path="/recherche-jobs-tchad",
        cv_storage_path="/sites/emploi.td/files/private/cv/",
    ),
    "burundi": CountryConfig(
        code="burundi",
        base_url="https://www.emploi.bi",
        jobs_search_path="/recherche-jobs-burundi",
        cv_storage_path="/sites/emploi.bi/files/private/cv/",
    ),
    "centrafrique": CountryConfig(
        code="centrafrique",
        base_url="https://www.emploi.cf",
        jobs_search_path="/recherche-jobs-centrafrique",
        cv_storage_path="/sites/emploi.cf/files/private/cv/",
    ),
    # ---------------------------------------------------------------------------
    # Afrique anglophone — paths /employer/ et /employers
    # ---------------------------------------------------------------------------
    "ghana": CountryConfig(
        code="ghana",
        base_url="https://www.ghanajob.com",
        jobs_search_path="/job-vacancies-search-ghana",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/ghanajob.com/files/private/cv/",
    ),
    "nigeria": CountryConfig(
        code="nigeria",
        base_url="https://www.nigeriajob.com",
        jobs_search_path="/job-vacancies-search-nigeria",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/nigeriajob.com/files/private/cv/",
    ),
    "egypt": CountryConfig(
        code="egypt",
        base_url="https://www.3amal.com",
        jobs_search_path="/job-vacancies-search-egypt",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/3amal.com/files/private/cv/",
    ),
    "ethiopia": CountryConfig(
        code="ethiopia",
        base_url="https://www.ethiopiawork.com",
        jobs_search_path="/job-vacancies-search-ethiopia",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/ethiopiawork.com/files/private/cv/",
    ),
    "kenya": CountryConfig(
        code="kenya",
        base_url="https://www.kenyajob.com",
        jobs_search_path="/job-vacancies-search-kenya",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/kenyajob.com/files/private/cv/",
    ),
    "uganda": CountryConfig(
        code="uganda",
        base_url="https://www.ugandajob.com",
        jobs_search_path="/job-vacancies-search-uganda",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/ugandajob.com/files/private/cv/",
    ),
    "rwanda": CountryConfig(
        code="rwanda",
        base_url="https://www.rwandajob.com",
        jobs_search_path="/job-vacancies-search-rwanda",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/rwandajob.com/files/private/cv/",
    ),
    "sudan": CountryConfig(
        code="sudan",
        base_url="https://www.sudancareers.com",
        jobs_search_path="/job-vacancies-search-sudan",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/sudancareers.com/files/private/cv/",
    ),
    "botswana": CountryConfig(
        code="botswana",
        base_url="https://www.botswajob.com",
        jobs_search_path="/job-vacancies-search-botswana",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/botswajob.com/files/private/cv/",
    ),
    "malawi": CountryConfig(
        code="malawi",
        base_url="https://www.malawijob.com",
        jobs_search_path="/job-vacancies-search-malawi",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/malawijob.com/files/private/cv/",
    ),
    "namibia": CountryConfig(
        code="namibia",
        base_url="https://www.namijob.com",
        jobs_search_path="/job-vacancies-search-namibia",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/namijob.com/files/private/cv/",
    ),
    "zambia": CountryConfig(
        code="zambia",
        base_url="https://www.zambiajob.com",
        jobs_search_path="/job-vacancies-search-zambia",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/zambiajob.com/files/private/cv/",
    ),
    "zimbabwe": CountryConfig(
        code="zimbabwe",
        base_url="https://www.zimbajob.com",
        jobs_search_path="/job-vacancies-search-zimbabwe",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/zimbajob.com/files/private/cv/",
    ),
    "liberia": CountryConfig(
        code="liberia",
        base_url="https://www.liberiawork.com",
        jobs_search_path="/job-vacancies-search-liberia",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/liberiawork.com/files/private/cv/",
    ),
    "sierra_leone": CountryConfig(
        code="sierra_leone",
        base_url="https://www.sierraleonejob.com",
        jobs_search_path="/job-vacancies-search-sierra-leone",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/sierraleonejob.com/files/private/cv/",
    ),
    "south_africa": CountryConfig(
        code="south_africa",
        base_url="https://www.zajob.com",
        jobs_search_path="/job-vacancies-search-south-africa",
        recruiters_path="/employers",
        recruiter_path_prefix="/recruiter/",
        cv_storage_path="/sites/zajob.com/files/private/cv/",
    ),
}
